### ISSUE TITLE
Make `DDL_SPI_ENABLE=DDL_ON` using platformio board_build.ddl

### ISSUE THREAD

**Issue by maxkondor** [shadow578/platform-hc32f46x#6]
Hello. I'm trying to add my motherboard (Anycubic Kobra Go) to the Marlin firmware. The motherboard has an SPI interface that communicates with the TFT screen. Can I enable it somehow from ddl setup? For now, I use the `-DDDL_SPI_ENABLE=DDL_ON` build flag, but this is no trusted way.

**Comment by shadow578** [comment]
Hi, see https://github.com/shadow578/framework-hc32f46x-ddl/blob/main/docs/config_options/DDL_SELECTION.md.

the option to enable the SPI ddl is `board_build.ddl.spi= true`.

**Comment by shadow578** [comment]
BTW, vendor examples for the SPI DDL are available in https://github.com/shadow578/hc32f460-documentation-and-sdk/tree/main/sdk/Driver%20library%20and%20samples/hc32f460_ddl_Rev2.1.0/example/ev_hc32f460_lqfp100_v2/spi

**Comment by maxkondor** [comment]
> BTW, vendor examples for the SPI DDL are available in https://github.com/shadow578/hc32f460-documentation-and-sdk/tree/main/sdk/Driver%20library%20and%20samples/hc32f460_ddl_Rev2.1.0/example/ev_hc32f460_lqfp100_v2/spi

Thank you very much. That MCU has a Chinese datasheet and I'm trying to understand Its peripheral part.

**Comment by shadow578** [comment]
english reference manual is also available in that repo at https://github.com/shadow578/hc32f460-documentation-and-sdk/blob/main/page-dump-new/documentation/reference%20manual/en/NATIVE_HC32F460_F45x_A460SeriesReferenceManual_Rev1.5.pdf
